spring:
  application:
    name: StudentMicroserviceClient
  web:
    error:
      whitelabel:
        enabled: false
eureka:
  client:
    service-url:
      default-zone: https://localhost:8760/eureka/
server:
  port: 3333
